### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by cmrichards** [danmartinez101/react-towel#2]
I've just tried the page at http://react-towel.surge.sh/ and nothing is being displayed.  It doesn't work with my own app too. There are no errors (except some deprecation warnings) in the console.  

Tested on Firefox 42.0 Ubuntu

Great work btw!

**Comment by danmartinez101** [comment]
@cmrichards I just pushed an update that includes a newer version of throw-in-the-towel which should support FF better.

Would you mind testing it again when you have a second? 

Thanks!

**Comment by danmartinez101** [comment]
I did a bit of testing here on El Capitan with FF 43

**Comment by cmrichards** [comment]
It works now - thanks
