### ISSUE TITLE
Upgrade React to 15

### ISSUE THREAD

**Issue by jackfranklin** [danmartinez101/react-towel#3]
Hey,

Is there any particular reason you've not upgraded this package to the latest version of React? I'm not asking because I'm annoyed by this, just if you're happy I'd love to make a PR that ups to v15 of React & React DOM :)

Jack

**Comment by danmartinez101** [comment]
I'd be very happy to merge a PR to upgrade :) 
 Thanks!

**Comment by danmartinez101** [comment]
Regarding why I haven't upgraded it myself:  
I mainly use https://github.com/danmartinez101/throw-in-the-towel
It is the same thing, just needs two extra script tags.

**Comment by jackfranklin** [comment]
Hey sorry I never got back to you - I've also tended to just use throw-in-the-towel. Sorry for the silence.

**Comment by danmartinez101** [comment]
No worries!
